[package]
name = "practice-chinese"
version = "0.1.0"
edition = "2021"

[dependencies]
dialoguer = { version = "0.11.0", features = ["fuzzy-select"] }
clap = "4.5.32"
serde_json = "1.0.140"
rand = "0.9.0"
foreach = "0.3.0"
crossterm = "0.28.1"
